### ISSUE TITLE
Crash when clicking on an event that doesn't have a forum link yet

### ISSUE THREAD

**Issue by TytaniumDev** [jrobinson3k1/Path-of-Exile-Racer#1]
The app will crash if the event doesn't have a forum link yet (events that are a few weeks out are usually like this).

This is a pretty easy fix that I can get to later if you don't get to it first!

**Comment by jrobinson3k1** [comment]
I didn't even realize that was possible, thanks for reporting! I'll put it in real quick tonight, there's a few other fixes I need to put in as well.
